/** @jsxRuntime classic */
/** @jsx jsx */
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { jsx } from "theme-ui";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tweed HR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <strong sx={{ color: "primary" }}>Tweed HR!</strong>
        </h1>

        <p className={styles.description}>No nonsense HR.</p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Pricing &rarr;</h2>
            <p>Spoiler: it&apos;s free. But you can buy us a coffee.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Contribute &rarr;</h2>
            <p>We&apos;re open source. Learn about contributing here.</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>See the site in action. Manage your employees with no stress.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            sx={{
              border: "1px solid",
              borderColor: "secondary",
            }}
          >
            <h2>
              <strong sx={{ color: "secondary" }}>Get started &rarr;</strong>
            </h2>
            <p>Click here and we&apos;ll get you up and running.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <nav
          sx={{
            variant: "containers.page",
            display: "flex",
            justifyContent: "space-evenly",
          }}
        >
          <Link href="/">About.</Link>
          <Link href="/">Careers.</Link>
        </nav>
      </footer>
    </div>
  );
}
